### ISSUE TITLE
Dark theme is broken

### ISSUE THREAD

**Issue by Eligioo** [onmax/nimiq-developer-center#34]
Toggling the dark theme doesn't work anymore

<img width="1488" alt="Screenshot 2024-06-27 at 12 46 27" src="https://github.com/nimiq/developer-center/assets/8634939/674e0b71-73ea-4ab2-b5aa-9a9023efb51b">

**Comment by onmax** [comment]
fixed!

**Comment by sisou** [comment]
@onmax Please link to the commit that fixed it.

**Comment by onmax** [comment]
https://github.com/onmax/nimiq-ui/commit/e77169151451b36d46eb6d8f10107d59169830c2
