### ISSUE TITLE
Fix broken links inside pages.

### ISSUE THREAD

**Issue by franciscodiaz4** [onmax/nimiq-developer-center#39]
1. https://www.nimiq.com/developers/build/ - Screenshot: https://app.screencast.com/m3Kj5iIUHLkxs
2. https://www.nimiq.com/developers/build/web-client/integrations/vite - Screenshot: https://app.screencast.com/vFCdoVoaVJkos
3. https://www.nimiq.com/developers/build/set-up-your-own-node/ - Screenshot: https://app.screencast.com/OOQWA9DwEOHX5
4. https://www.nimiq.com/developers/build/set-up-your-own-node/becoming-a-validator - Screenshot: https://app.screencast.com/6HBgHIrvDHOdD
5. https://www.nimiq.com/developers/build/set-up-your-own-node/rpc-docs/ - Screenshot: https://app.screencast.com/CnD9h4gmUdOvG

**Comment by onmax** [comment]
Thank you!

Fixed. Do you know of a JS tool that we can use to automate this process? 

It should check dead links ONLY after build and much preferably as a vite plugin
