### ISSUE TITLE
Fix side navigation bar behaviour on build page.

### ISSUE THREAD

**Issue by franciscodiaz4** [onmax/nimiq-developer-center#44]
Description:
Navigation bar jumps everytime the user clicks on any of the links.

Steps:
1. Go to https://www.nimiq.com/developers/build/
2. Click on any of the side navigation links.

Video: https://app.screencast.com/igJIYcKjLAc7K

**Comment by onmax** [comment]
Navigation will be rebuild from scratch. When that happens this issue might be gone
