### ISSUE TITLE
Create a "Web client" VS "RPC" page

### ISSUE THREAD

**Issue by onmax** [onmax/nimiq-developer-center#8]
Hey @ines-toupeira, as Janine mentioned in the #7, it might be confusing to offer two clients.

Do you think it is ok to create a page that compares both client.

We could also add:
- some examples on when to use one and when to use another.
- Some do's and don'ts

If you think is a good idea, would you like to write it or should I create first a draft and then you update it?

**Comment by ines-toupeira** [comment]
I think it's a good idea, I'll work on it
